### ISSUE TITLE
Could Not Be Compiled (Timezones)

### ISSUE THREAD

**Issue by squeakybatboi** [TheCommieAxolotl/BetterDiscord-Stuff#99] opened 2024-08-05 07:46 UTC
### Addon

Timezones

### What happened?

installed, immediately given an error that prevents it from being enabled

### What Discord version do you have this issue on?

Stable

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'default')
    at plugin (betterdiscord://plugins/Timezones.plugin.js:143:113)
    at eval (betterdiscord://plugins/Timezones.plugin.js:313:22)
    at eval (betterdiscord://plugins/Timezones.plugin.js:314:13)
    at eval (betterdiscord://plugins/Timezones.plugin.js:315:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment] 2024-08-05 11:06
Duplicate of #95 
Already fixed.

**Comment by TheCommieAxolotl** [comment] 2024-08-05 11:06
Download the latest version from GitHub

**Closed by TheCommieAxolotl** 2024-08-05 11:06 UTC
Labels: bug
