### ISSUE TITLE
[Bug] Timezones option does not appear in DMs

### ISSUE THREAD

**Issue by maenDisease** [TheCommieAxolotl/BetterDiscord-Stuff#21] opened 2023-02-13 00:06 UTC
### Addon

Timezones

### What happened?

The Timezones option doesn't appear when right clicking users from the DM sidebar list and DMs chat, however it does work from the friends list

### What Discord version do you have this issue on?

Stable, PTB, Canary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JuniorGenius** [comment] 2023-02-13 07:19
This is a duplicate of #18

**Comment by Drflash55** [comment] 2023-02-13 07:23
Not necessarily. This went more in-depth as to the potential problem, as the other one was too generic as to figure out what the issue was. Also, it doesn't only work from the friends list, it's everywhere but the DM Sidebar, and in DM history with users that it fails to show up on.

**Comment by TheCommieAxolotl** [comment] 2023-02-13 08:03
Fixed in [6c11b28](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/6c11b281e85f110cf42976dd32cae262a9021e3e)

**Closed by TheCommieAxolotl** 2023-02-13 08:03 UTC
Labels: bug
