### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Aghneel** [TheCommieAxolotl/BetterDiscord-Stuff#12] opened 2022-10-24 12:41 UTC
### Addon

BetterSyntax.plugin.js

### What happened?

Plugin crashes when switch channel.

### What Discord version do you have this issue on?

Stable

### Logs

```shell
http://0x0.st/oxU4.png
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment] 2022-10-24 18:53
Duplicate of #11

**Closed by TheCommieAxolotl** 2022-10-24 18:53 UTC
Labels: bug

**Comment by TheCommieAxolotl** [comment] 2022-10-24 23:07
Sorry, that's my mistake. I forgot to do a version bump so the update wasn't shown to many people, i've just done that now.
